#!/bin/bash
#SBATCH -J RunTrialstest # job name
#SBATCH -o RunTrialsMPI.o%j       # output and error file name (%j expands to jobID)
#SBATCH -n 32              # total number of mpi tasks requested
#SBATCH -p development     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:05:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=lacava@tacc.utexas.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
ibrun ./RunTrialsMPI.out              # run the MPI executable named a.out
